################################################################################
###                                                                          ###
### Created by Martin Genet                                                  ###
###                                                                          ###
### École Polytechnique, Palaiseau, France                                   ###
###                                                                          ###
################################################################################

name: notebook

channels:
  - conda-forge
  - defaults

dependencies:
# dolfin_warp
  - expat=2.5
  - fenics=2019.1.0
  - gnuplot=5.4
  - matplotlib=3.5
  - meshio=5.3
  - mpi4py=3.1.3
  - numpy=1.21.6 # MG20221220: later numpy versions seem incompatible with itkwidgets 0.32
  - pandas=1.3
  - python=3.10
  - scipy=1.9
  - vtk=9.2

# jupyter
  - ipydatawidgets=4.3.2
  - ipywidgets=7.6.5 # MG20221226: cf. https://github.com/InsightSoftwareConsortium/itkwidgets/pull/590/files # MG20230601: Somehow this is still needed, despite the updated itkwidgets version…
  - itkwidgets=0.32.6
  # MG20240123: Specified all these versions based on the 2023 build to get ipywidgets and itkwidgets to properly interact
  - jupyter=1.0.0
  - jupyter_client=7.4.8
  - jupyter_console=6.4.4
  - jupyter_contrib_core=0.4.0
  - jupyter_contrib_nbextensions=0.5.1
  - jupyter_core=5.1.3
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.6
  - jupyter_nbextensions_configurator=0.4.1
  - jupyter_server=2.0.6
  - jupyter_server_terminals=0.4.3
  # MG20240123: Specified all these versions based on the 2023 build to get ipywidgets and itkwidgets to properly interact
  - jupyterlab=3.5.2 # MG20230602: This seems to be needed as well, otherwise jupyter does not start on binder
  - notebook=6.4.6 # MG20221226: cf. https://github.com/InsightSoftwareConsortium/itkwidgets/pull/590/files # MG20230601: Somehow this is still needed, despite the updated itkwidgets version…
  - traitlets=5.6.0 # MG20221226: cf. https://github.com/InsightSoftwareConsortium/itkwidgets/pull/590/files # MG20230601: Somehow this is still needed, despite the updated itkwidgets version…

  - pip
  - pip:
    - dolfin_warp

variables:
    CPATH: /srv/conda/envs/notebook/include/vtk-9.2 # MG20250418: Somehow repo2docker does not seem to take into account the environment variable defined in environment.yml…
