################################################################################
###                                                                          ###
### Created by Martin Genet                                                  ###
###                                                                          ###
### École Polytechnique, Palaiseau, France                                   ###
###                                                                          ###
################################################################################

name: notebook

channels:
  - conda-forge
  - defaults

dependencies:
# python
  - mpi4py=3.1.3 # MG20220906: To avoid mpi warnings in FEniCS, cf. https://fenicsproject.discourse.group/t/runtimewarning-mpi4py-mpi-file-size-changed-may-indicate-binary-incompatibility-expected-32-from-c-header-got-40-from-pyobject-def-compile-class-cpp-data-mpi-comm-mpi-comm-world/6496 # MG20220906: Note that 3.0.3 leads to a `RuntimeError: Error when importing mpi4py`, but 3.1.3 seems to work.
  - numpy=1.21.6 # MG20221220: later numpy versions seem incompatible with itkwidgets 0.32
  - python=3.8
  - scipy=1.9
  - sympy=1.9

# jupyter
  - ipywidgets=7.6 # MG20221226: cf. https://github.com/InsightSoftwareConsortium/itkwidgets/pull/590/files # MG20230601: Somehow this is still needed, despite the updated itkwidgets version…
  - itkwidgets=0.32
  # MG20240123: Specified all these versions based on the 2023 build to get ipywidgets and itkwidgets to properly interact
  - jupyter=1.0.0
  - jupyter_client=7.4.8
  - jupyter_console=6.4.4
  - jupyter_contrib_core=0.4.0
  - jupyter_contrib_nbextensions=0.5.1
  - jupyter_core=5.1.3
  - jupyter_highlight_selected_word=0.2.0
  - jupyter_latex_envs=1.4.6
  - jupyter_nbextensions_configurator=0.4.1
  - jupyter_server=2.0.6
  - jupyter_server_terminals=0.4.3
  # MG20240123: Specified all these versions based on the 2023 build to get ipywidgets and itkwidgets to properly interact
  - jupyterlab=3.5 # MG20230602: This seems to be needed as well, otherwise jupyter does not start on binder
  - notebook=6.4 # MG20221226: cf. https://github.com/InsightSoftwareConsortium/itkwidgets/pull/590/files # MG20230601: Somehow this is still needed, despite the updated itkwidgets version…

# coding stuff
  - git=2.39

# computing stuff
  - expat=2.5
  - fenics=2019.1.0
  - vtk=9.0 # MG20201223: Need to correspond to the environment variable CPATH # MG20220628: Apparently there is some kind of conflict between vtk9.1 & libstdc++.so.6 in Ubuntu 20.04… # MG20221220: Apparently there is some kind of conflict between vtk9.1 & itkwidgets 0.32…

# plotting stuff
  - matplotlib=3.5
  - gnuplot=5.4

  - pip
  - pip:
  # python
    - numpy==1.21.6 # MG20240605: meshio seems to be installing a newer numpy…
    - zstd

  # computing stuff
    - gmsh==4.9.0
    - meshio==5.3.4

  # tracking stuff
    - dolfin_warp

variables:
    CPATH: /srv/conda/envs/notebook/include/vtk-9.0
