################################################################################
###                                                                          ###
### Created by Martin Genet                                                  ###
###                                                                          ###
### École Polytechnique, Palaiseau, France                                   ###
###                                                                          ###
################################################################################

name: notebook

channels:
  - conda-forge
  - defaults

dependencies:
# python
  - mpi4py=3.1.3 # MG20220906: To avoid mpi warnings in FEniCS, cf. https://fenicsproject.discourse.group/t/runtimewarning-mpi4py-mpi-file-size-changed-may-indicate-binary-incompatibility-expected-32-from-c-header-got-40-from-pyobject-def-compile-class-cpp-data-mpi-comm-mpi-comm-world/6496 # MG20220906: Note that 3.0.3 leads to a `RuntimeError: Error when importing mpi4py`, but 3.1.3 seems to work.
  - numpy=1.21.5 # MG20221220: later numpy versions seem incompatible with itkwidgets 0.32
  - python
  - scipy
  - sympy

# jupyter
  - "ipywidgets<8" # MG20221226: cf. https://github.com/InsightSoftwareConsortium/itkwidgets/pull/590/files # MG20230601: Somehow this is still needed, despite the updated itkwidgets version…
  - itkwidgets=0.32.6
  - jupyter
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - "jupyterlab<4" # MG20230602: This seems to be needed as well, otherwise jupyter does not start on binder
  - "notebook<6.5" # MG20221226: cf. https://github.com/InsightSoftwareConsortium/itkwidgets/pull/590/files # MG20230601: Somehow this is still needed, despite the updated itkwidgets version…

# coding stuff
  - git

# computing stuff
  - fenics=2019.1.0
  - gmsh
  - meshio
  - vtk=9.0 # MG20201223: Need to correspond to the environment variable CPATH # MG20220628: Apparently there is some kind of conflict between vtk9.1 & libstdc++.so.6 in Ubuntu 20.04… # MG20221220: Apparently there is some kind of conflict between vtk9.1 & itkwidgets 0.32…

# plotting stuff
  - matplotlib
  - gnuplot

  - pip
  - pip:
  # python
    - numpy==1.21.5 # MG20240605: meshio seems to be installing a newer numpy…
    - zstd

  # computing stuff
    - gmsh
    - meshio

  # tracking stuff
    - dolfin_warp

variables:
    CPATH: /srv/conda/envs/notebook/include/vtk-9.0
